import type { ValidateFunction } from "ajv";
import type { JSONObject } from '../../types';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NotifyWebhookPayload =
  | {
      sq_state: "approved";
      approved_since: number;
      order_ref: string;
      order_ref_1: string;
      product_code: string;
      channelId: string;
      transactionId: string;
      checkoutId: string;
      [k: string]: unknown;
    }
  | {
      sq_state: "needs_review";
      needs_review_since: number;
      order_ref: string;
      order_ref_1: string;
      product_code: string;
      channelId: string;
      transactionId: string;
      checkoutId: string;
      [k: string]: unknown;
    };

declare const ValidateNotifyWebhookPayload: ValidateFunction<NotifyWebhookPayload>;
export default ValidateNotifyWebhookPayload;