import type { ValidateFunction } from "ajv";
import type { JSONObject } from '../../types';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrderUpdateRequest {
  order: {
    /**
     * String containing the cancellation reason when clearing an order.
     */
    cancellation_reason?: null | "change" | "change_payment_method" | "customer_cancel" | "out_of_stock" | "other";
    /**
     * Fields describing the merchant and the store integration
     */
    merchant: {
      id: string | number;
      /**
       * Permanent identifier for the store where the checkout takes place. Example: \"maquinista\". (string)** Mandatory for multistore merchants, optional for physical stores, not permitted for others
       */
      store_ref?: string;
    };
    /**
     * Order id(s) used by the merchan
     */
    merchant_reference: {
      order_ref_1?: string | number;
      /**
       * Merchant reference 2. Example: \"0080-1234-4343-5353\".
       */
      order_ref_2?: string | number;
    };
    unshipped_cart: {
      /**
       * Total value with tax of the items listed below. Example: 5097.
       */
      order_total_with_tax: number;
      currency: string;
      /**
       * List of unshipped items in the order. The list can contain zero or more instances of each item type.
       */
      items?: (
        | {
            type?: "product";
            /**
             * Name of category. Will not be shown to shopper. Useful against fraud. Example: \"ipod-accesorios\".
             */
            category?: string;
            /**
             * Product description. Will not be shown to shopper. Useful against fraud. Example: \"Este estuche de cuero de última moda ...\".
             */
            description?: string;
            /**
             * Can the buyer access or consume the product without a physical delivery? PDFs, e-tickets, software, etc are downloadable. Example: false.
             */
            downloadable: boolean;
            /**
             * Name of manufacturer. Will not be shown to shopper. Useful against fraud. Example: \"Apple\".
             */
            manufacturer?: string;
            /**
             * A description to include in the payment instructions. Example: \"Leather Case (iPod nano) - Negro / Chocolate\".
             */
            name: string;
            /**
             * A product is perishable if it loses its value if it is not delivered on time. Examples are fresh fruit and physical tickets. Example: false.
             */
            perishable?: boolean;
            /**
             * A product is personalized if it is irreversibly customized in a way that makes it less appealing to most people other than the buyer. Example: false.
             */
            personalized?: boolean;
            /**
             * Price with tax for one item. Example: 3030.
             */
            price_with_tax: number;
            /**
             * Id from database. Will not be shown to shopper. Sometimes useful if 'reference' varies too much over time. Example: \"6\".
             */
            product_id?: string | number;
            /**
             * The number of items ordered by the shopper. Example: 2.
             */
            quantity: number;
            /**
             * A public product id for this item. Example: \"12-123-1234\".
             */
            reference: string | number;
            /**
             * A product is restockable if it can be sold to someone else if returned in good condition.  Foodstuff is generally not restockable. Example: true.
             */
            restockable?: boolean;
            /**
             * Subscription period of item in months. Example: 24.
             */
            subscription_period?: number;
            /**
             * Total subscription cost per month (subscription_price_per_item * quantity) Example: 1000.
             */
            subscription_price?: number;
            /**
             * Subscription cost per month per item. Example: 500.
             */
            subscription_price_per_item?: number;
            /**
             * Name of supplier or provider. Will not be shown to shopper. Useful against fraud. Example: \"Mayorista Makro\".
             */
            supplier?: string;
            /**
             * Price with tax for the amount in the order. Due to rounding, this might not be exactly quantity × price_with_tax. Example: 6060.
             */
            total_with_tax: number;
            /**
             * A reference to the tracking in which this item will be handed. Example: \"first\".
             */
            tracking_reference?: string;
            /**
             * Product page URL in your shop. Might be shown to shopper. Useful for customer service. Example: \"http://shop.example.com/ipod-accesorios/leather-case\".
             */
            url?: string;
          }
        | {
            type: "handling";
            /**
             * A name to describe this item. More specific is better, i.e. prefer 'Correos' to 'Envío'. Example: \"SEUR entrega en 24 horas\".
             */
            name: string;
            /**
             * A unique code that refers to this item. Does not have to exist in the shop catalogue. Example: \"seur24\".
             */
            reference: string | number;
            /**
             * Price with tax for this handling service. Example: 242.
             */
            total_with_tax: number;
          }
        | {
            type: "invoice_fee";
            /**
             * Price with tax for the invoice (i1) service. Do not use with product codes other than i1. Example: 295.
             */
            total_with_tax: number;
          }
        | {
            type: "discount";
            /**
             * A name to describe this discount. Might be displayed in the payment instructions. Example: \"50 % off the full basket!\".
             */
            name: string;
            /**
             * A unique code that refers to this discount. Can be the discount code. Example: \"HALFOFF\".
             */
            reference: string | number;
            /**
             * Amount that this discount changes the cart value with tax. Should be negative. Example: -750.
             */
            total_with_tax: number;
          }
        | {
            type: "other_payment";
            name: string;
            /**
             * A code that refers to this \"other\" payment. (An \"other\" payment means that the shopper \" \\\n          \"has paid part of the cart using some other means of payment, like cash or credit card.) Example: \"CASH\". (string or int
             */
            reference: string | number;
            /**
             * Amount that this payment changes the cart value with tax. Should use opposite sign of any item it pays for. Example: -750.
             */
            total_with_tax: number;
          }
        | {
            type: "service";
            /**
             * True for services that can be fully (or sufficiently) enjoyed without a physical delivery. For instance, a course with only digital material. Example: false.
             */
            downloadable: boolean;
            /**
             * Maximum time, from the start of the service, for the service to be rendered or ended. Example: \"P3M15D\".
             */
            ends_in: string;
            /**
             * Maximum date for the service to be rendered or ended. Example: \"2017-06-30\".
             */
            ends_on: string;
            /**
             * A name to describe this service. Might be displayed in the payment instructions. Example: \"Networks Administrator Course\".
             */
            name: string;
            /**
             * Price with tax for one item. Example: 3030.
             */
            price_with_tax: number;
            /**
             * The number of items ordered by the shopper. Example: 1.
             */
            quantity: number;
            /**
             * A public id for this service. Example: \"NETWORKS-ADMIN-101\".
             */
            reference: string | number;
            /**
             * True when the service has been rendered Example: false.
             */
            rendered?: boolean;
            /**
             * Name of supplier or provider. Example: \"Acme Formación\".
             */
            supplier?: string;
            /**
             * Price with tax for the amount in the order. Due to rounding, this might not be exactly quantity × price_with_tax. Example: 75020.
             */
            total_with_tax: number;
          }
        | {
            type: "subscriber_fee";
            /**
             * A description to include in the payment instructions. Example: \"Subscription fee\".
             */
            name: string;
            /**
             * Price with tax for one item. Example: 3030.
             */
            price_with_tax?: number;
            /**
             * The number of items ordered by the shopper. Example: 2.
             */
            quantity?: number;
            /**
             * A public product id for this item. Example: \"12-123-1234\".
             */
            reference?: string | number;
            /**
             * Subscription period of item in months. Example: 24.
             */
            subscription_period?: number;
            /**
             * Total subscription cost per month (subscription_price_per_item * quantity) Example: 1000.
             */
            subscription_price?: number;
            /**
             * Subscription cost per month per item. Example: 500.
             */
            subscription_price_per_item?: number;
            /**
             * Price with tax for the amount in the order. Due to rounding, this might not be exactly quantity × price_with_tax. Example: 6060.
             */
            total_with_tax: number;
          }
      )[];
    };
    shipped_cart: {
      /**
       * Total value with tax of the items listed below. Example: 5097.
       */
      order_total_with_tax: number;
      currency: string;
      /**
       * List of unshipped items in the order. The list can contain zero or more instances of each item type.
       */
      items?: (
        | {
            type?: "product";
            /**
             * Name of category. Will not be shown to shopper. Useful against fraud. Example: \"ipod-accesorios\".
             */
            category?: string;
            /**
             * Product description. Will not be shown to shopper. Useful against fraud. Example: \"Este estuche de cuero de última moda ...\".
             */
            description?: string;
            /**
             * Can the buyer access or consume the product without a physical delivery? PDFs, e-tickets, software, etc are downloadable. Example: false.
             */
            downloadable: boolean;
            /**
             * Name of manufacturer. Will not be shown to shopper. Useful against fraud. Example: \"Apple\".
             */
            manufacturer?: string;
            /**
             * A description to include in the payment instructions. Example: \"Leather Case (iPod nano) - Negro / Chocolate\".
             */
            name: string;
            /**
             * A product is perishable if it loses its value if it is not delivered on time. Examples are fresh fruit and physical tickets. Example: false.
             */
            perishable?: boolean;
            /**
             * A product is personalized if it is irreversibly customized in a way that makes it less appealing to most people other than the buyer. Example: false.
             */
            personalized?: boolean;
            /**
             * Price with tax for one item. Example: 3030.
             */
            price_with_tax: number;
            /**
             * Id from database. Will not be shown to shopper. Sometimes useful if 'reference' varies too much over time. Example: \"6\".
             */
            product_id?: string | number;
            /**
             * The number of items ordered by the shopper. Example: 2.
             */
            quantity: number;
            /**
             * A public product id for this item. Example: \"12-123-1234\".
             */
            reference: string | number;
            /**
             * A product is restockable if it can be sold to someone else if returned in good condition.  Foodstuff is generally not restockable. Example: true.
             */
            restockable?: boolean;
            /**
             * Subscription period of item in months. Example: 24.
             */
            subscription_period?: number;
            /**
             * Total subscription cost per month (subscription_price_per_item * quantity) Example: 1000.
             */
            subscription_price?: number;
            /**
             * Subscription cost per month per item. Example: 500.
             */
            subscription_price_per_item?: number;
            /**
             * Name of supplier or provider. Will not be shown to shopper. Useful against fraud. Example: \"Mayorista Makro\".
             */
            supplier?: string;
            /**
             * Price with tax for the amount in the order. Due to rounding, this might not be exactly quantity × price_with_tax. Example: 6060.
             */
            total_with_tax: number;
            /**
             * A reference to the tracking in which this item will be handed. Example: \"first\".
             */
            tracking_reference?: string;
            /**
             * Product page URL in your shop. Might be shown to shopper. Useful for customer service. Example: \"http://shop.example.com/ipod-accesorios/leather-case\".
             */
            url?: string;
          }
        | {
            type: "handling";
            /**
             * A name to describe this item. More specific is better, i.e. prefer 'Correos' to 'Envío'. Example: \"SEUR entrega en 24 horas\".
             */
            name: string;
            /**
             * A unique code that refers to this item. Does not have to exist in the shop catalogue. Example: \"seur24\".
             */
            reference: string | number;
            /**
             * Price with tax for this handling service. Example: 242.
             */
            total_with_tax: number;
          }
        | {
            type: "invoice_fee";
            /**
             * Price with tax for the invoice (i1) service. Do not use with product codes other than i1. Example: 295.
             */
            total_with_tax: number;
          }
        | {
            type: "discount";
            /**
             * A name to describe this discount. Might be displayed in the payment instructions. Example: \"50 % off the full basket!\".
             */
            name: string;
            /**
             * A unique code that refers to this discount. Can be the discount code. Example: \"HALFOFF\".
             */
            reference: string | number;
            /**
             * Amount that this discount changes the cart value with tax. Should be negative. Example: -750.
             */
            total_with_tax: number;
          }
        | {
            type: "other_payment";
            name: string;
            /**
             * A code that refers to this \"other\" payment. (An \"other\" payment means that the shopper \" \\\n          \"has paid part of the cart using some other means of payment, like cash or credit card.) Example: \"CASH\". (string or int
             */
            reference: string | number;
            /**
             * Amount that this payment changes the cart value with tax. Should use opposite sign of any item it pays for. Example: -750.
             */
            total_with_tax: number;
          }
        | {
            type: "service";
            /**
             * True for services that can be fully (or sufficiently) enjoyed without a physical delivery. For instance, a course with only digital material. Example: false.
             */
            downloadable: boolean;
            /**
             * Maximum time, from the start of the service, for the service to be rendered or ended. Example: \"P3M15D\".
             */
            ends_in: string;
            /**
             * Maximum date for the service to be rendered or ended. Example: \"2017-06-30\".
             */
            ends_on: string;
            /**
             * A name to describe this service. Might be displayed in the payment instructions. Example: \"Networks Administrator Course\".
             */
            name: string;
            /**
             * Price with tax for one item. Example: 3030.
             */
            price_with_tax: number;
            /**
             * The number of items ordered by the shopper. Example: 1.
             */
            quantity: number;
            /**
             * A public id for this service. Example: \"NETWORKS-ADMIN-101\".
             */
            reference: string | number;
            /**
             * True when the service has been rendered Example: false.
             */
            rendered?: boolean;
            /**
             * Name of supplier or provider. Example: \"Acme Formación\".
             */
            supplier?: string;
            /**
             * Price with tax for the amount in the order. Due to rounding, this might not be exactly quantity × price_with_tax. Example: 75020.
             */
            total_with_tax: number;
          }
        | {
            type: "subscriber_fee";
            /**
             * A description to include in the payment instructions. Example: \"Subscription fee\".
             */
            name: string;
            /**
             * Price with tax for one item. Example: 3030.
             */
            price_with_tax?: number;
            /**
             * The number of items ordered by the shopper. Example: 2.
             */
            quantity?: number;
            /**
             * A public product id for this item. Example: \"12-123-1234\".
             */
            reference?: string | number;
            /**
             * Subscription period of item in months. Example: 24.
             */
            subscription_period?: number;
            /**
             * Total subscription cost per month (subscription_price_per_item * quantity) Example: 1000.
             */
            subscription_price?: number;
            /**
             * Subscription cost per month per item. Example: 500.
             */
            subscription_price_per_item?: number;
            /**
             * Price with tax for the amount in the order. Due to rounding, this might not be exactly quantity × price_with_tax. Example: 6060.
             */
            total_with_tax: number;
          }
      )[];
    };
    /**
     * A list of trackings for the order
     */
    trackings?: (
      | {
          /**
           * Address line 1 for the store. Example: \"1600 Pennsylvania Avenue\".
           */
          address_line_1?: string;
          /**
           * Address line 2 for the store. Example: \"5º\".
           */
          address_line_2?: string;
          /**
           * When this delivery was available in the store. Example: \"2014-02-05T13:21:22+01:00\".
           */
          available_at?: string;
          /**
           * City. Example: \"Barcelona\".
           */
          city?: string;
          /**
           * Country code. Example: \"ES\".
           */
          country_code?: string;
          /**
           * When this delivery was handed. When set, the delivey is considered to be handed. Example: \"2014-02-05T19:21:22+01:00\".
           */
          delivered_at?: string;
          /**
           * Permanent identifier for the operator that handed the delivery. Example: \"123-009\".
           */
          operator_ref?: string;
          /**
           * Postal code. Example: \"08013\".
           */
          postal_code?: string;
          /**
           * Internal tracking reference. Example: \"first\".
           */
          reference: string;
          /**
           * State or region. Example: \"Barcelona\".
           */
          state?: string;
          /**
           * Permanent identifier for the store that handled this delivery. Example: \"maquinista\".
           */
          store_ref?: string;
          /**
           * Tracking number. Example: \"AB331\".
           */
          tracking_number?: string;
          type: "pickup_store";
        }
      | {
          /**
           * Address line 1 for the pickup point. Example: \"1600 Pennsylvania Avenue\".
           */
          address_line_1?: string;
          /**
           * Address line 2 for the pickup point. Example: \"5º\".
           */
          address_line_2?: string;
          /**
           * When this delivery was available in the store. Example: \"2014-02-05T13:21:22+01:00\".
           */
          available_at?: string;
          /**
           * City. Example: \"Barcelona\".
           */
          city?: string;
          /**
           * Country code. Example: \"ES\".
           */
          country_code?: string;
          /**
           * When this delivery was handed. When set, the delivey is considered to be handed. Example: \"2014-02-05T19:21:22+01:00\".
           */
          delivered_at?: string;
          /**
           * Permanent identifier for the operator that handed the delivery. Example: \"123-009\".
           */
          operator_ref?: string;
          /**
           * Postal code. Example: \"08013\".
           */
          postal_code?: string;
          /**
           * Tracking reference. Example: \"second\".
           */
          reference: string;
          /**
           * State or region. Example: \"Barcelona\".
           */
          state?: string;
          /**
           * Permanent identifier for the store that handled this delivery. Example: \"maquinista\".
           */
          store_ref?: string;
          /**
           * Tracking number. Example: \"AB331\".
           */
          tracking_number?: string;
          type: "pickup_point";
        }
      | {
          /**
           * The name of the company that handled this delivery. Example: \"SEUR\".
           */
          carrier: string;
          /**
           * When this delivery was handed. When set, the delivey is considered to be handed. Example: \"2014-02-05T19:21:22+01:00\".
           */
          delivered_at?: string;
          /**
           * Internal tracking reference. Example: \"third\".
           */
          reference: string;
          /**
           * Tracking number. Example: \"TX123\".
           */
          tracking_number?: string;
          /**
           * Tracking URL. Example: \"https://logistics.es/TX123\".
           */
          tracking_url?: string;
          type: "postal";
        }
    )[];
    /**
     * Fields describing the delivery address
     */
    delivery_address?: {
      /**
       * Delivery address line 1. Example: \"C/ Aragó 383\".
       */
      address_line_1: string;
      /**
       * Delivery address line 2. Example: \"5º\".
       */
      address_line_2: string;
      /**
       * Delivery address city. Example: \"Barcelona\".
       */
      city: string;
      /**
       * Shopper company name.
       */
      company: string;
      /**
       * Delivery address country code. Example: \"ES\".
       */
      country_code: string;
      /**
       * Extra handling information that the shopper adds to the order. Example: \"I'm home between 9 and 12.\".
       */
      extra?: string;
      given_names: string;
      /**
       * Shopper mobile phone. Only use this field if the shopper indicated that this number is a mobile phone. Example: \"615 615 615\".
       */
      mobile_phone?: string;
      /**
       * Shopper phone. Can be a mobile phone. Example: \"933 033 033\".
       */
      phone?: string;
      /**
       * Delivery address address postal code. Example: \"08013\".
       */
      postal_code: string;
      /**
       * Shopper region or state. Example: \"Barcelona\".
       */
      state?: string;
      /**
       * Shopper's last names for delivery. Example: \"Barroso Rajoy\".
       */
      surnames: string;
      /**
       * Shopper VAT number. Example: \"B12345\".
       */
      vat_number?: string;
    };
    /**
     * Delivery method used on the purchase
     */
    delivery_method?: {
      /**
       * Days it takes to deliver the goods. Example: \"¡Entrega día siguiente!\".
       */
      days?: string;
      /**
       * If goods are delivered to the buyer's home or office and not to a pick-up place. Example: true.
       */
      home_delivery?: boolean;
      name: string;
      /**
       * Company or agent that performs the delivery. Example: \"Correos\".
       */
      provider?: string;
    };
    /**
     * Fields describing the invoice address
     */
    invoice_address?: {
      /**
       * Invoice address line 1.
       */
      address_line_1: string;
      /**
       * Invoice address line 2.
       */
      address_line_2: string;
      /**
       * Invoice address city.
       */
      city: string;
      /**
       * Shopper company name.
       */
      company: string;
      /**
       * Invoice address country code. Example: \"ES\".
       */
      country_code: string;
      /**
       * Extra handling information that the shopper adds to the order. Example: \"I'm home between 9 and 12.\".
       */
      extra?: string;
      given_names: string;
      /**
       * Shopper mobile phone. Only use this field if the shopper indicated that this number is a mobile phone. Example: \"615 615 615\".
       */
      mobile_phone?: string;
      /**
       * Shopper phone. Can be a mobile phone. Example: \"933 033 033\".
       */
      phone?: string;
      /**
       * Invoice address address postal code.
       */
      postal_code: string;
      /**
       * Shopper region or state. Example: \"Tarragona\".
       */
      state?: string;
      /**
       * Shopper's last names for invoice. Example: \"Barroso Rajoy\".
       */
      surnames: string;
      /**
       * Shopper VAT number. Example: \"B12345\".
       */
      vat_number?: string;
    };
    /**
     * Fields describing the customer
     */
    customer?: {
      /**
       * Customer company name.
       */
      company?: string;
      /**
       * Date when this customer was added to the shop database, in ISO-8601 format. Example: \"2013-08-15T21:07:37+01:00\".
       */
      created_at?: string;
      /**
       * Customer date of birth in ISO-8601 format. Example: \"1980-01-20\".
       */
      date_of_birth?: string;
      /**
       * Customer email. Example: \"nisse@example.com\".
       */
      email: string;
      given_names: string;
      /**
       * Customer ip number. Example: \"12.23.34.45\".
       */
      ip_number: string;
      /**
       * Customer language code. Example: \"es-ES\".
       */
      language_code: string;
      /**
       * Is the customer logged in? Use 'unknown' if your platform cannot check whether the user is logged in or not Example: true.
       */
      logged_in: false | true | "unknown";
      /**
       * Customer's national identity number. For Spanish DNI, please include final letter. Example: \"13003009L\".
       */
      nin?: string;
      /**
       * A validation code printed in the physical DNI or NIE. Required for multistore merchants and physical stores. See the FAQs to know more. Example: \"15012018F2\".
       */
      nin_control?: string;
      /**
       * List of customer's previous orders in this shop.
       */
      previous_orders?: {
        /**
         * Total order amount including tax. Example: 4656.
         */
        amount: number;
        /**
         * Previous order's country code. Example: \"ES\".
         */
        country_code?: string;
        /**
         * Date (and time, if available) when this order was created or delivered, in ISO-8601 format. Example: \"2013-06-11T12:27:40+02:00\".
         */
        created_at: string;
        /**
         * Currency name for amount. Example: \"EUR\".
         */
        currency: string;
        /**
         * Mapped payment methods. Use one of CC (for credit cards), PP (for PayPal), TR (for bank wire), COD (for cash on delivery, contrareembolso), SQ (SeQura). For other methods, use O/ plus a name, e.g. 'O/postal_giro' Example: \"PP\".
         */
        payment_method?: string;
        /**
         * Payment method as reported by the platform. Example: \"PayPal\".
         */
        payment_method_raw?: string;
        /**
         * Previous order's delivery address postal code. Example: \"08013\".
         */
        postal_code?: string;
        /**
         * The status of the order as reported in the platform. Example: \"Shipped\".
         */
        raw_status?: string;
        /**
         * The mapped status value. Use one of 'processing', 'shipped' or 'cancelled' Example: \"shipped\".
         */
        status?: string;
      }[];
      /**
       * The merchant's rating of this customer. 0 to 100, inclusive, where 0 is \"cannot be trusted\" and 100 is \"very trustworthy\". Example: 100.
       */
      rating?: number;
      /**
       * Customer reference number in the shop's database. Example: 123.
       */
      ref?: string | number;
      /**
       * Customer surnames. Example: \"Barroso Rajoy\".
       */
      surnames: string;
      /**
       * Customer title and/or gender. Use the one of 'mr', 'ms', 'mrs', 'miss' or 'mx' that is closest to the information supplied by the customer. If none of these can be inferred, use the title that the customer entered as-is.  See also 'Note about title' in the docs. Example: \"mr\".
       */
      title?: string;
      /**
       * Date when this customer was updated in the shop database, in ISO-8601 format. Example: \"2013-09-27T16:50:25+01:00\".
       */
      updated_at?: string;
      /**
       * Customer browser. Example: \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36\".
       */
      user_agent: string;
      /**
       * Shopper VAT number. Example: \"B12345\".
       */
      vat_number?: string;
      /**
       * Fields describing the customer's vehicl
       */
      vehicle?: {
        /**
         * Brand from customer's vehicle Example: \"Volkswagen\".
         */
        brand?: string;
        /**
         * First registration date plaque from customer's vehicle Example: \"2000-03-25\".
         */
        first_registration_date?: string;
        /**
         * Frame identificator from customer's vehicle Example: \"VF1RFD00653635032\".
         */
        frame?: string;
        /**
         * Model from customer's vehicle Example: \"Beetle\".
         */
        model?: string;
        plaque: string;
      };
    };
    /**
     * Fields describing the store platform
     */
    platform: {
      /**
       * DB used. Example: \"mysql\".
       */
      db_name: string;
      /**
       * Version of the DB. Example: \"1.2.3\".
       */
      db_version: string;
      name: string;
      /**
       * PHP interpreter version. Example: \"5.4.1.7\".
       */
      php_version?: string;
      /**
       * Version of the plugin or platform module.  If you don't use explicit versioning, use a release date instead. Example: \"1.0.2\".
       */
      plugin_version?: string;
      /**
       * uname of the shop server. In PHP, use php_uname(). Example: \"Darwin roatan.local 13.0.0 Darwin Kernel Version 13.0... x86_64\".
       */
      uname: string;
      /**
       * Version of the platform.  If you don't use explicit versioning, use a release date instead. Example: \"1.1\".
       */
      version: string;
    };
  };
}

declare const ValidateOrderUpdateRequest: ValidateFunction<OrderUpdateRequest>;
export default ValidateOrderUpdateRequest;