import type { ValidateFunction } from "ajv";
import type { JSONObject } from '../../types';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PaymentMethodGetForOrderResponse {
  payment_options: {
    title: string;
    description: string;
    methods: {
      product: string;
      campaign?: string;
      title: string;
      long_title: string;
      claim: string;
      description?: string;
      icon: string;
      cost_description?: string;
      starts_at: string;
      ends_at: string;
      min_amount: number;
      max_amount?: number;
      [k: string]: unknown;
    }[];
    icon: unknown;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

declare const ValidatePaymentMethodGetForOrderResponse: ValidateFunction<PaymentMethodGetForOrderResponse>;
export default ValidatePaymentMethodGetForOrderResponse;