import type { ValidateFunction } from "ajv";
import type { JSONObject } from '../../types';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JSON = JSONObject;
export type SyncWebhookAppErrors = SyncWebhookAppError[];
export type TransactionActions = ("CHARGE" | "REFUND" | "CANCEL")[];

export interface TransactionProcessSessionResponse {
  pspReference?: string;
  data?: {
    sequraOrderResponse: JSON;
    errors?: SyncWebhookAppErrors;
    [k: string]: unknown;
  };
  result:
    | "AUTHORIZATION_SUCCESS"
    | "AUTHORIZATION_FAILURE"
    | "AUTHORIZATION_REQUEST"
    | "AUTHORIZATION_ACTION_REQUIRED"
    | "CHARGE_SUCCESS"
    | "CHARGE_FAILURE"
    | "CHARGE_REQUEST"
    | "CHARGE_ACTION_REQUIRED";
  amount: number;
  time?: string;
  externalUrl?: string;
  message?: string;
  actions?: TransactionActions;
}
export interface SyncWebhookAppError {
  code?: string;
  message?: string;
  details?: JSON;
}

declare const ValidateTransactionProcessSessionResponse: ValidateFunction<TransactionProcessSessionResponse>;
export default ValidateTransactionProcessSessionResponse;