import type { ValidateFunction } from "ajv";
import type { JSONObject } from '../../types';
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TransactionProcessSessionRequestData {
  merchantReference?: string;
}

declare const ValidateTransactionProcessSessionRequestData: ValidateFunction<TransactionProcessSessionRequestData>;
export default ValidateTransactionProcessSessionRequestData;